[32mINFO    [0m root:__init__.py:27 功能的名称为：test_ryvue 功能的描述为：None
[1m[31mERROR   [0m root:test_ryvue.py:76 userManagement_073断言失败，用例数据为：{'userName': 'userManagement_073', 'nickName': 'userManagement_073', 'password': '123456', 'status': '0', 'postIds': [5], 'roleIds': []}期望数据为：{'msg': '操作失败', 'code': 500}服务器返回的期望数据：{"msg":"操作成功","code":200}
[1m[31mERROR   [0m root:__init__.py:33 断言失败