[32mINFO    [0m root:__init__.py:27 功能的名称为：test_ryvue 功能的描述为：None
[31m[1mERROR   [0m root:test_ryvue.py:70 userManagement_026断言失败，用例数据为：{'userName': 'userManagement_026', 'nickName': 'userManagement_026', 'password': '123456', 'status': '0', 'postIds': [], 'roleIds': [], 'email': 'a@bc'}期望数据为：{'msg': '邮箱格式不正确', 'code': 500}服务器返回的期望数据：{"msg":"操作成功","code":200}
[31m[1mERROR   [0m root:__init__.py:33 断言失败