[32mINFO    [0m root:__init__.py:27 功能的名称为：test_ryvue 功能的描述为：None
[31m[1mERROR   [0m root:test_ryvue.py:70 roleManagement_019断言失败，用例数据为：{'roleName': 'roleManagement_019', 'roleKey': 'roleManagement_019', 'roleSort': 3, 'status': '', 'menuIds': [], 'deptIds': [], 'menuCheckStrictly': True, 'deptCheckStrictly': True, 'remark': 'remark'}期望数据为：{'msg': '操作失败', 'code': 500}服务器返回的期望数据：{"msg":"\n### Error updating database.  Cause: java.sql.SQLException: Field 'status' doesn't have a default value\n### The error may exist in URL [jar:file:/ruoyi/app/ruoyi-admin.jar!/BOOT-INF/lib/ruoyi-system-3.8.7.jar!/mapper/system/SysRoleMapper.xml]\n### The error may involve com.ruoyi.system.mapper.SysRoleMapper.insertRole-Inline\n### The error occurred while setting parameters\n### SQL: insert into sys_role(            role_name,       role_key,       role_sort,             menu_check_strictly,       dept_check_strictly,             remark,       create_by,      create_time    )values(            ?,       ?,       ?,             ?,       ?,             ?,       ?,      sysdate()    )\n### Cause: java.sql.SQLException: Field 'status' doesn't have a default value\n; Field 'status' doesn't have a default value; nested exception is java.sql.SQLException: Field 'status' doesn't have a default value","code":500}
[31m[1mERROR   [0m root:__init__.py:33 断言失败